#!/bin/sh
# rc.lxc init script
# Written by Matteo Bernardini <ponce@slackbuilds.org>
#
# This script checks for the presence of the parameter lxc.start.auto
# in the available container configurations: if it's set to 1 the
# container is started (in an auto-detached screen session if
# screen is available) when rc.lxc is called with the "start" param.
#
# To stop the container it uses lxc-attach to execute /sbin/halt
# inside of it.
#
# Modified by Roberto Puzzanghera https://notes.sagredo.eu for managing
# unprivileged containers and to handle systemd containers on a
# slackware host.
#

. /usr/share/lxc/lxc.functions
. /usr/local/bin/my_lxc-common
export PATH=$PATH:/bin:/usr/bin:/usr/local/bin

start_lxc() {
  for CONTAIN in $(lxc-ls); do
    # check if autostart is on
    if [ "$(lxc-info -n $CONTAIN -c lxc.start.auto)" = "lxc.start.auto = 1" ]; then
      echo "Starting LXC container ${CONTAIN}."
      lxu $CONTAIN
      if [ $? -gt 0 ]; then
        return 2
      fi
    fi
  done
}

stop_lxc() {
  for CONTAIN in $(lxc-ls); do
    OWNER=$(owner $CONTAIN)
    if [ "$(sudo -u $OWNER lxc-info -s -n $CONTAIN 2> /dev/null | grep RUNNING$)" ]; then
      echo "Stopping LXC container ${CONTAIN}."
      lxd $CONTAIN
    fi
    if [ $? -gt 0 ]; then
      return 2
    fi
  done
}

restart_lxc() {
  stop_lxc
  sleep 2
  start_lxc
}

mount_systemd() {
  # trick to fake a systemd cgroup mount
  # it can cause side effects on host and guest
  # reboot to revert
  # https://www.linuxquestions.org/questions/slackware-14/lxc-4-0-x-and-libcgroups-for-slackware-current-4175697576/#post6273843
  echo "Mounting systemd cgroup..."
  [ -h /sys/fs/cgroup/systemd ] && rm -f /sys/fs/cgroup/systemd && rm -f /run/systemd
  mkdir -p /sys/fs/cgroup/systemd
  mkdir -p /run/systemd
  mount -t cgroup -o none,name=systemd systemd /sys/fs/cgroup/systemd 2>/dev/null
  mkdir -p /sys/fs/cgroup/unified
  mount -t cgroup2 -o rw,nosuid,nodev,noexec,relatime,nsdelegate cgroup2 /sys/fs/cgroup/unified 2>/dev/null
}


case "$1" in
'start')
  start_lxc
  ;;
'stop')
  stop_lxc
  ;;
'restart')
  restart_lxc
  ;;
'mount')
  mount_systemd
  ;;
*)
  echo "usage $0 start|stop|restart|mount"
esac
